### ISSUE TITLE
実装方針

### ISSUE THREAD

**Issue by abap34** [abap34/ECG-classification#1]
基本的なファイル構成は、
- data
- models 
- logs
- src
です。

## data
dataをそのまま入れます。ルールが不明なので手元だけで、レポジトリには入れないこと。

## models
models/ 以下に,
`wavenet.py`, `resnet.py`のようにファイルを追加していってください。
各.pyクラスは次のように実装してください。
- モデルのclassを１つ実装すること
- `model.__init__`は、` def __init__(self,  params):`という引数を受け取ること
- `model.fit(self, train_x, train_y, val_x, val_y, fold_index)`を作成。
具体的には、`models/wavenet.py`を参照。

##  logs

```
logs/{model_name}/losses/
logs/{model_name}/models/
logs/{model_name}config.yaml
```

にlogを保存してください。
- `losses`以下に各foldの学習曲線とlossのcsvファイル
-  `models`以下に各foldの学習済みモデル
-  `config.yaml`は`train.py`に渡したコマンドライン引数を保存する
ような形です。

## src
- `train.py`
からなります。
`train.py`にコマンドライン引数でパラメータを渡して訓練します。
例) `train.py --name WaveNet --epoch 25 --batch_size 8`

**Comment by chizuchizu** [comment]
## Training

`src/model.py`の`BaseModel`というクラス内に学習からログの吐き出しまでの関数を作成しました。

`src/train.py`では次のように`BaseModel`を用いてモデルを定義しています。

```python
# モデル定義
 model = MODEL_NAMES_DICT[param.model_name](param)
```

## Models
`models` 以下には、`wavenet.py`、`resnet.py`のようにファイルを追加してください。

そして、2つのコードを書く必要があります。

1. `get_model`関数

ファイル内に次のような`get_model`関数を作成してください。

  - 引数は`input_shape`
  - 返り値は`model.compile`済みのKerasモデル

2. 継承クラス

下のコードを貼り付けてください。

```python
class Model(BaseModel):
    def __init__(self, params):
        super().__init__(params, get_model())
```

もし、訓練や推論時に特別な動作をさせたいというときには関数をオーバーライドすることもできます。

**Comment by abap34** [comment]
基本的な実装は完了したのでcloseします。
